"""Tax-credit zone sections for the county pages, the statewide incentives page, and the county panel data.

Reads pipelines/incentives/programs.json (hand-entered, cited) and zones.json (generated by
pipelines/incentives/build.mjs from the official GIS layers). Imported by build.py.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

INCENTIVES_DIR = Path(__file__).resolve().parents[1] / "incentives"

# Coverage of a county's land area by enterprise zones.
FULL, MOST = 95.0, 50.0


def load() -> tuple:
    programs = json.loads((INCENTIVES_DIR / "programs.json").read_text())
    zones = json.loads((INCENTIVES_DIR / "zones.json").read_text())
    return programs, {c["name"]: c for c in zones["counties"]}


def link(programs: dict, sid: str, text: Optional[str] = None) -> str:
    s = programs["sources"][sid]
    return f"[{text or s['title']}]({s['url']})"


def tract_url(geoid: str) -> str:
    return f"https://data.census.gov/profile?g=1400000US{geoid}"


def where(t: dict) -> str:
    if t["places"]:
        return ", ".join(t["places"])
    return f"rural, near {t['near']}" if t.get("near") else "rural"


def coverage_phrase(pct: float) -> str:
    if pct >= FULL:
        return "all or nearly all of the county"
    if pct >= MOST:
        return f"most of the county (about {pct:.0f}% of its land)"
    if pct >= 1:
        return f"part of the county (about {pct:.0f}% of its land)"
    return f"a small part of the county (under 1% of its land)" if pct > 0 else "none of the county"


def summary(z: dict) -> str:
    """One line for the county panel and the statewide table."""
    ez = z["enterpriseZone"]
    oz = z["opportunityZones"]
    parts = []
    if ez["zones"]:
        names = " and ".join(x["zone"] for x in ez["zones"])
        parts.append(f"Enterprise zone ({names}) covers {coverage_phrase(ez['coveragePct'])}"
                     + (", with enhanced rural credits" if z["enhancedRural"] == "whole county" else "")
                     + (f"; enhanced rural credits in {z['enhancedRural'][0].lower() + z['enhancedRural'][1:]}" if z["enhancedRural"] not in (None, "whole county") else "")
                     + ".")
    else:
        parts.append("No enterprise zone.")
    n2, n1 = len(oz["oz2Nominated"]), len(oz["oz1"])
    if n2:
        rural = sum(t["rural"] for t in oz["oz2Nominated"])
        rural_txt = f", {rural} rural" if rural and rural < n2 else (", rural" if rural else "")
        parts.append(f"{n2} opportunity zone tract{'s' if n2 > 1 else ''} nominated for 2027{rural_txt}.")
    elif oz["oz2Eligible"]:
        parts.append(f"No 2027 opportunity zone nominated ({oz['oz2Eligible']} eligible tract{'s' if oz['oz2Eligible'] > 1 else ''}).")
    else:
        parts.append("No tract eligible for the 2027 opportunity zones.")
    if n1:
        parts.append(f"{n1} current opportunity zone tract{'s' if n1 > 1 else ''} through 2028.")
    if z["ruralJumpStart"] == "zone":
        parts.append("Rural Jump-Start zone.")
    return " ".join(parts)


def panel_record(z: dict) -> dict:
    """Short facts for the app's county panel (hosting.json)."""
    ez, oz = z["enterpriseZone"], z["opportunityZones"]
    return {
        "summary": summary(z),
        "enterpriseZone": " and ".join(x["zone"] for x in ez["zones"]) or None,
        "enterpriseZonePct": ez["coveragePct"],
        "enhancedRural": z["enhancedRural"],
        "ruralJumpStart": z["ruralJumpStart"],
        "oz1Tracts": len(oz["oz1"]),
        "oz2Tracts": [{"geoid": t["geoid"], "where": where(t), "rural": t["rural"]} for t in oz["oz2Nominated"]],
    }


def render_section(name: str, programs: dict, z: dict) -> str:
    ez, oz = z["enterpriseZone"], z["opportunityZones"]
    ezp = programs["enterpriseZones"]
    zones_info = ezp["zones"]
    lines = [
        "## Tax-credit zones for land development",
        "",
        f"> {summary(z)}",
        "",
        "Location-based state and federal incentives that can help pay for building on, improving or doing business on a "
        "parcel here. What each program pays for, and how it applies to land, is on "
        "[Tax-Credit Zones](../18-incentive-zones.md). Zone lines don't follow parcel lines, so confirm a specific address with "
        f"the administrator or OEDIT's {link(programs, 'ezmap', 'enterprise zone map')}.",
        "",
        "| Program | Here |",
        "|---|---|",
    ]

    if ez["zones"]:
        cells = []
        for x in ez["zones"]:
            info = zones_info[x["zone"]]
            contact = ", ".join(v for v in (info["phone"], f"<{info['email']}>" if info["email"] else "") if v)
            org = f"[{info['administrator']}]({info['url']})" if info["url"] else info["administrator"]
            note = "" if x["listedByOedit"] else " OEDIT's administrator list doesn't name this county for the zone, but the zone map overlaps it. Confirm with the administrator."
            cells.append(f"**{x['zone']}**: {coverage_phrase(x['coveragePct'])}. Administrator: {org}, {contact}.{note}")
        ez_cell = " ".join(cells)
    else:
        ez_cell = "None. The county isn't in any of the 16 zones on the 2026-2036 map."
    lines.append(f"| Enterprise zone (2026-2036 map) | {ez_cell} |")

    erez = z["enhancedRural"]
    erez_cell = "Yes, the whole county." if erez == "whole county" else (f"{erez}." if erez else "No.")
    lines.append(f"| Enhanced rural enterprise zone ({programs['enhancedRural']['years']}) | {erez_cell} |")

    rjs = z["ruralJumpStart"]
    rjs_cell = {"zone": "Yes, a participating zone.",
                "eligible, not joined": "Eligible as a distressed county, but hasn't joined the program."}.get(rjs, "No.")
    if z["justTransitionTier1"]:
        rjs_cell += f" Tier 1 coal transition community ({z['justTransitionTier1']}): larger new-business grants."
    lines.append(f"| Rural Jump-Start | {rjs_cell} |")

    n1, n2 = len(oz["oz1"]), len(oz["oz2Nominated"])
    lines.append(f"| Opportunity zones, current map (through 2028-12-31) | {n1 or 'No'} tract{'s' if n1 != 1 else ''}. |")
    oz2_cell = (f"{n2} tract{'s' if n2 != 1 else ''} nominated, out of {oz['oz2Eligible']} eligible. Treasury certification is expected by the end of November 2026."
                if n2 else (f"None nominated, out of {oz['oz2Eligible']} eligible." if oz["oz2Eligible"] else "No eligible tracts."))
    for g in oz["oz2RejectedOffList"]:
        oz2_cell += f" The Governor also submitted off-list tract {g}; Treasury rejected it on 2026-09-10."
    lines.append(f"| Opportunity zones, 2027 map (from 2027-01-01) | {oz2_cell} |")
    lines.append("")

    # Towns, when the zone covers only part of the county.
    towns = ez["towns"]
    if ez["zones"] and ez["coveragePct"] < FULL and towns:
        inside = [t for t in towns if t["inZonePct"] >= 90]
        partly = [t for t in towns if 10 <= t["inZonePct"] < 90]
        outside = [t for t in towns if t["inZonePct"] < 10]
        fmt = lambda ts, show: ", ".join(f"{t['name']} (about {t['inZonePct']:.0f}%)" if show else t["name"] for t in ts)
        lines += ["### Enterprise zone by town", "",
                  "Share of each incorporated town's area inside the zone. Unincorporated land between towns is often outside.", ""]
        if inside:
            lines.append(f"- **In the zone:** {fmt(inside, False)}")
        if partly:
            lines.append(f"- **Partly:** {fmt(partly, True)}")
        if outside:
            lines.append(f"- **Outside or nearly outside:** {fmt(outside, False)}")
        lines.append("")

    tracts: Dict[str, dict] = {}
    for t in oz["oz1"]:
        tracts.setdefault(t["geoid"], {"t": t})["oz1"] = t
    for t in oz["oz2Nominated"]:
        tracts.setdefault(t["geoid"], {"t": t})["oz2"] = t
    if tracts:
        lines += ["### Opportunity zone tracts", "",
                  "| Tract | Where | Size | Current map (to 2028) | 2027 map (nominated) |", "|---|---|---|---|---|"]
        for geoid in sorted(tracts):
            e = tracts[geoid]
            t = e.get("oz2") or e["t"]
            col = lambda k: ("Yes, rural" if e[k]["rural"] else "Yes") if k in e else "—"
            lines.append(f"| [{geoid}]({tract_url(geoid)}) | {where(t)} | {t['sqmi']:g} sq mi | {col('oz1')} | {col('oz2')} |")
        lines += ["",
                  "The current map uses 2010 tracts and the 2027 map uses 2020 tracts, so a tract number on both maps can have "
                  "different boundaries. \"Rural\" is the H.R. 1 definition, which gets the larger 2027 tax break and the lower "
                  "improvement threshold.", ""]

    lines += ["### For a land purchase here", ""]
    lines += [f"- {b}" for b in land_notes(z)]
    lines += ["",
              f"Sources: {link(programs, 'ezadmins', 'OEDIT EZ administrators')}, {link(programs, 'ezgis', 'OEDIT EZ map layer')}, "
              f"{link(programs, 'ez', 'OEDIT EZ program')}, {link(programs, 'rjs', 'Rural Jump-Start')}, "
              f"{link(programs, 'oz', 'OEDIT Opportunity Zones (nominated list)')}, {link(programs, 'ozelig', 'Treasury eligible tracts')}, "
              f"{link(programs, 'hudoz', 'HUD 2018 OZ tracts')}. All checked {programs['checkedAt']}. "
              "Zone coverage and town names are measured from those maps and Census 2020 place boundaries by "
              "`pipelines/incentives/build.mjs`.", ""]
    return "\n".join(lines)


def land_notes(z: dict) -> List[str]:
    ez, oz = z["enterpriseZone"], z["opportunityZones"]
    notes = []
    if ez["zones"]:
        notes.append("Enterprise zone credits reward what a business **does** on the land: buying equipment (3% investment credit), "
                     "hiring, rehabbing a vacant commercial building (25%, up to $50,000). Buying and holding raw land earns nothing. "
                     "Pre-certify with the administrator **before** the spending.")
        if z["enhancedRural"]:
            notes.append("Enhanced rural status adds to the new-employee credit, which matters for a staffed operation such as a campground or farm stay.")
    if z["ruralJumpStart"] == "zone":
        notes.append("Rural Jump-Start fits a brand-new business that sells outside the county and will hire. It doesn't fit a solo rental, "
                     "and a business that competes with an existing local one can be challenged.")
    if oz["oz2Nominated"] or oz["oz1"]:
        rural = any(t["rural"] for t in oz["oz2Nominated"])
        notes.append("Opportunity zones reward investing **capital gains** through a qualified opportunity fund. Raw land doesn't have to be "
                     "doubled in value, but buying it with no plan to improve it within 30 months fails the anti-abuse rule.")
        if rural:
            notes.append("Rural 2027 tracts here get the 30% basis step-up (instead of 10%) for funds holding 90% rural assets, and existing "
                         "buildings only need 50% improvement instead of 100%.")
    if not ez["zones"] and not oz["oz2Nominated"] and not oz["oz1"]:
        notes.append("None of the state or federal location-based programs here applies. County-level incentives, such as fee waivers or "
                     "local property-tax deals, are case by case; ask the county's economic development office.")
    return notes


def render_statewide(programs: dict, zones: Dict[str, dict], rows: List[tuple]) -> str:
    """wiki/18-incentive-zones.md: the programs explained, then all 64 counties."""
    L = lambda sid, text=None: link(programs, sid, text)
    erez = programs["enhancedRural"]
    rjs = programs["ruralJumpStart"]
    table = ["| County | Region | Enterprise zone | Enhanced rural | Rural Jump-Start | OZ tracts, current | OZ tracts, 2027 (eligible) |",
             "|---|---|---|---|---|---|---|"]
    for name, region, slug in rows:
        z = zones[name]
        ez = z["enterpriseZone"]
        ez_cell = f"{' / '.join(x['zone'] for x in ez['zones'])}, {ez['coveragePct']:.0f}%" if ez["zones"] else "—"
        rural2 = sum(t["rural"] for t in z["opportunityZones"]["oz2Nominated"])
        n2 = len(z["opportunityZones"]["oz2Nominated"])
        oz2 = f"{n2}{f' ({rural2} rural)' if rural2 else ''} of {z['opportunityZones']['oz2Eligible']}"
        rjs_cell = {"zone": "Zone", "eligible, not joined": "Eligible"}.get(z["ruralJumpStart"], "—")
        erez_cell = {"whole county": "Yes", None: "—"}.get(z["enhancedRural"], "Part")
        table.append(f"| [{name}](counties/{slug}.md#tax-credit-zones-for-land-development) | {region} | {ez_cell} | {erez_cell} | {rjs_cell} | "
                     f"{len(z['opportunityZones']['oz1']) or '—'} | {oz2} |")

    return f"""<!-- Generated by pipelines/hosting/build.py from pipelines/incentives/. Edit those files, not this one. -->
# Tax-Credit Zones: Enterprise Zones, Opportunity Zones & Rural Jump-Start

Some Colorado land sits inside zones where the state or federal government pays part of the cost of developing it,
or of running a business on it. This page explains the three programs that matter for buying and developing land,
then lists every county. Each [county page](counties/README.md) has a **Tax-credit zones** section with the
details: which zone, how much of the county it covers, which towns are in it, and each opportunity zone tract.

> **This is research, not tax advice.** The programs below are tax credits and deferrals with pre-certification
> steps, deadlines and recapture rules. Talk to a Colorado CPA before you count on any of them in a purchase price.

Checked {programs['checkedAt']}. Next review {programs['nextReview']}: {programs['nextReviewWhy']}

## Which program fits which plan

| Your plan for the land | Program that can help | What it pays |
|---|---|---|
| Build or expand a business there (campground, farm stay, shop, workshop) | Enterprise zone | State income-tax credits on equipment, hiring, training and rehab |
| Rehab an old vacant commercial building | Enterprise zone | 25% of rehab costs, up to $50,000 in credits |
| Start a new business that sells outside the county and hires | Rural Jump-Start | 100% relief of state income and sales tax and county business personal property tax, plus a $15,000-$25,000 grant |
| Reinvest a capital gain (from stocks, a business or property sale) into development | Opportunity zone | Deferred tax on the gain, a basis step-up, and no tax on the new investment's growth after 10 years |
| Buy land and hold it | None | None of these programs pays for owning land without developing or using it |

## Enterprise zones (state)

Colorado has 16 enterprise zones, run by 19 local administrators, in areas with high unemployment, low income or
slow population growth. OEDIT redesignated every zone for **2026-01-01 to 2036-01-01**
({L('ezredes', 'redesignation')}, {L('ezgis', 'zone map layer')}). Businesses in a zone can earn state income-tax credits
({L('ez', 'OEDIT program page')}; {L('doreztax', 'DOR credit guide')}):

- **Investment tax credit:** 3% of business personal property (equipment, not land or buildings).
- **New employee credit:** $1,100 per net new employee, more in enhanced rural zones and for agricultural processors.
- **Employer health insurance credit:** $1,000 per net new insured employee, first two years.
- **Job training credit:** 12% of eligible training costs.
- **Vacant commercial building rehabilitation credit:** 25% of rehab costs for a commercial building at least 20 years old and vacant at least two years (up to $50,000 in credits).
- **Research and development credit:** 3% of the increase in R&D spending.
- **Commercial vehicle credit:** 1.5% of new commercial trucks and trailers.
- **Contribution projects:** anyone who donates to a certified local zone project gets a 25% credit on cash (12.5% in kind), up to $100,000 a year.

A business must **pre-certify** with its zone administrator through OEDIT's portal before the activity, every tax
year, then certify afterward and file the certificate with its Colorado return.

**Enhanced rural enterprise zones** ({erez['years']}) earn larger new-employee credits. They are {', '.join(erez['counties'])},
plus parts of Montrose and San Miguel (the Tier 1 coal transition areas only). OEDIT updates the list every two years.

## Opportunity zones (federal)

Opportunity zones are low-income census tracts where investing **capital gains** through a qualified opportunity fund
defers and reduces federal tax, and Colorado follows the federal treatment. There are two maps ({L('oz', 'OEDIT')}):

- **Current map:** 126 tracts designated in 2018 ({L('hudoz', 'HUD layer')}), open for investment through **2028-12-31**.
  {len(programs['opportunityZones']['oz1Rural']['tracts'])} of them count as rural under the new definition ({L('n2550', 'IRS Notice 2025-50')}),
  so investments there now get the lower 50% improvement threshold.
- **2027 map:** H.R. 1 (July 2025) made the program permanent, with a new map every 10 years. Treasury found
  {sum(z['opportunityZones']['oz2Eligible'] for z in zones.values())} eligible tracts in Colorado in April 2026 ({L('ozelig', 'list')}),
  then raised the count to 362, which set the 25% cap at 91. On 2026-09-28 the Governor nominated the maximum,
  **91**, including 28 rural ({L('ozpr', 'press release')}). The per-county eligible counts here come from the April list.
  Treasury is expected to certify them by the end of November 2026, and they open for investment on **2027-01-01**.
  See OEDIT's {L('ozgis', 'OZ 2.0 GIS tool')} for the map.

Benefits under the 2027 rules ({L('oz', 'OEDIT')}; {L('eig', 'EIG summary')}):

- **Deferral:** tax on the original gain is deferred for five years from the date of investment.
- **Step-up:** after five years, 10% of the deferred gain is forgiven, or **30%** through a qualified rural opportunity fund
  (at least 90% of its assets in rural tracts).
- **Exclusion:** hold the fund investment 10 years and its growth is tax-free (capped at 30 years).
- **Substantial improvement:** an existing building must be improved by 100% of its basis within 30 months, or **50%**
  in a rural tract.

**For land:** unimproved land in a zone doesn't itself have to be substantially improved, but land bought with no
expectation of improving it more than an insubstantial amount within 30 months fails the anti-abuse rule
([26 CFR 1.1400Z2(d)-2(b)(4)(iv)](https://www.law.cornell.edu/cfr/text/26/1.1400Z2(d)-2)). In practice the
fund has to build something, such as housing, cabins, a campground or a business, not hold the land.

## Rural Jump-Start (state)

For a **new** business in a participating distressed county that exports goods or services outside the county,
partners with a sponsoring college or economic development group, and hires 3-5 new full-time employees at the
county's average wage or more. It can't compete with an existing business in the county or a neighboring distressed
county. Benefits are 100% relief of state income tax, state sales and use tax, county (and participating
municipal) business personal property tax, and state income tax for qualified new hires, plus a matching grant
of up to $15,000, or $25,000 in Tier 1 coal transition communities. Tax benefits run through
{rjs['taxThrough']} and grants through {rjs['grantsThrough']} ({L('rjs', 'OEDIT')}).

- **Participating zones:** {', '.join(rjs['zones'])}.
- **Eligible but not yet participating:** {', '.join(rjs['eligibleNotJoined'])}.

## All counties

Enterprise zone percentages are the share of the county's land inside a zone, measured from OEDIT's 2026-2036 map.
"OZ tracts, 2027" counts nominated tracts out of Treasury's eligible tracts.

{chr(10).join(table)}

## How this data is built

- `pipelines/incentives/programs.json`: hand-entered facts from the sources above (zone administrators, enhanced
  rural and Rural Jump-Start lists, nominated tracts), each with a source id.
- `pipelines/incentives/build.mjs`: downloads the zone and tract maps and Census 2020 town boundaries, measures the
  overlaps with mapshaper, and writes `pipelines/incentives/zones.json`.
- `pipelines/hosting/build.py`: renders this page, the section on each county page, and the county panel data.

```sh
node pipelines/incentives/build.mjs --refresh   # re-download the maps (after Treasury certifies the 2027 tracts, say)
python3 pipelines/hosting/build.py              # regenerate the wiki and app data
```
"""
